ffmpeg -i crash1.wav crash1.m4a
ffmpeg -i crash2.wav crash2.m4a
ffmpeg -i crash3.wav crash3.m4a
ffmpeg -i hat_closed_1.wav hat_closed_1.m4a
ffmpeg -i hat_closed_2.wav hat_closed_2.m4a
ffmpeg -i hat_closed_3.wav hat_closed_3.m4a
ffmpeg -i hat_foot.wav hat_foot.m4a
ffmpeg -i hat_open_1.wav hat_open_1.m4a
ffmpeg -i hat_open_2.wav hat_open_2.m4a
ffmpeg -i hat_ring.wav hat_ring.m4a
ffmpeg -i kick2.wav kick2.m4a
ffmpeg -i ride1.wav ride1.m4a
ffmpeg -i ride2.wav ride2.m4a
ffmpeg -i snare_ghost_ringing.wav snare_ghost_ringing.m4a
ffmpeg -i snare_ghost.wav snare_ghost.m4a
ffmpeg -i snare_tippin.wav snare_tippin.m4a
ffmpeg -i snare1.wav snare1.m4a
ffmpeg -i snare2.wav snare2.m4a
ffmpeg -i snareslide.wav snareslide.m4a
ffmpeg -i stick.wav stick.m4a
ffmpeg -i tom1.wav tom1.m4a
ffmpeg -i tom2.wav tom2.m4a
ffmpeg -i tom3.wav tom3.m4a
